### ISSUE TITLE
Error with creating board

### ISSUE THREAD

**Issue by akurdyukov** [overbaard/overbaard#116]
I installed Overbaard and tried creating new board. I got error `Http failure response for https://tracker.unitedtraders.team/rest/overbaard/1.0/boards?full=true: 500 OK` after I invoke config.

Details in DevTools shows error:
```
message: Internal server error: There was a SQL exception thrown by the Active Objects library:
Database:
	- name:PostgreSQL
	- version:9.5.8
	- minor version:5
	- major version:9
Driver:
	- name:PostgreSQL Native Driver
	- version:PostgreSQL 9.4.1212

org.postgresql.util.PSQLException: ERROR: column "name" does not exist
  Position: 66
```

**Comment by kabir** [comment]
Interesting, if you enable TRACE logging for `org.overbaard.jira` and `org.overbaard.jira.prototype`, do you get a stack trace showing more context of the problem?

**Comment by kabir** [comment]
Also, can you please attach your board configuration (assuming it does not contain anything sensitive)?

**Comment by akurdyukov** [comment]
The board is

**Comment by akurdyukov** [comment]
> Interesting, if you enable TRACE logging for `org.overbaard.jira` and `org.overbaard.jira.prototype`, do you get a stack trace showing more context of the problem?

I added these logs using System > Logging and Profiling section. But the only additional line I got are:
```

**Comment by kabir** [comment]
I'll try with postgresql here

**Comment by kabir** [comment]
I can reproduce the error, and think I have a fix. I just need to test a few different permutations, and if that goes well should be able to do another release next week. Keep an eye out on https://twitter.com/Overbaard for the release announcement.

Thanks for reporting it!

**Comment by kabir** [comment]
@akurdyukov I think it should be fixed now. Please let me know if you have any further problems, or need help in getting set up!

**Comment by akurdyukov** [comment]
Great, everything works now.
