### ISSUE TITLE
Rank view - make bars wider

### ISSUE THREAD

**Issue by rsvoboda** [overbaard/overbaard#43]
Rank view - make bars wider

Currently they are high, but too narrow.

I would like to have it wider by 50 - 100 %

**Comment by kabir** [comment]
Currently they have a hardcoded size.
Perhaps it should fit 100% of the screen width, with a minimum size (so that boards with a large amount of states can still scroll)?

**Comment by rsvoboda** [comment]
+1

If it turn out to be a bit weird on large resolutions, could be max size/width also introduced?

**Comment by kabir** [comment]
This will be too fiddly in combination with what I have planned for 
https://github.com/overbaard/overbaard/issues/42
