### ISSUE TITLE
Search + hide non-matching && swimlanes enabled - missing item

### ISSUE THREAD

**Issue by rsvoboda** [overbaard/overbaard#49]
Item is not shown when using Search feature with Hide non-matching enabled && Swimlane - Component

The same query but with swimlane disabled shows expected item 

Not present in swimlane view: https://issues.jboss.org/overbaard/index.html#/board?board=EAP-7.3.0.GA&swimlane=component&pt.TD=TODO,In%20Progress,Review&s.text=runtime&s.hide=true&hidden=6,7,9

Works in non-swimlane view: https://issues.jboss.org/overbaard/index.html#/board?board=EAP-7.3.0.GA&pt.TD=TODO,In%20Progress,Review&s.text=runtime&s.hide=true&hidden=6,7,9

**Comment by kabir** [comment]
Digging a bit into it earlier, if I have swimlanes set to labels or components and the matching issue is in the 'None' swimlane, it does not show up. If it is in one of the other swimlanes it shows up.

Also, if I do the Target Release swimlane it shows up regardless of the swimlane being 'None' or another one. There is a difference between these two cases in that an issue supports having more than one component or label, but only one Target Release.

**Comment by rsvoboda** [comment]
I can confirm this issue is no longer present.
Thank you for the fix, this was quick !
