### ISSUE TITLE
Rank view - show item number

### ISSUE THREAD

**Issue by jstourac** [overbaard/overbaard#59]
With current rank view, one cannot easily see what is the number of the issue in the queue. If you scroll through the list of the items, you can say e.g. that 'this issue is already quite down in the rank view', but if you want to know its actual order, you have to count manually.

Note: this would be really cool if such rank number is shown also in case I use some kind of filter - e.g. text search or so. Navigation through that with regard the priority would be easier then.

**Comment by kabir** [comment]
@jstourac Jira doesn't actually expose the Rank field, it is some secret number calculated in obscure ways. However, I guess for the rank view I could count them myself if that is what you mean?

Or would you also like to see this in the kanban view?

**Comment by jstourac** [comment]
Yeah, what I meant was to calculate it specifically for the Rank view by yourself and show it next to the each item.

To see this number also in kanban view might be benefical too, although, I guess that main place where this really helps is Rank view itself.

**Comment by kabir** [comment]
Good, in the Rank View it is straight-forward, in the Kanban View it would be harder :)

**Comment by rsvoboda** [comment]
We need proper ranking :( So server side is probably the right way

Having it just in rank view is so-so.
But probably better something than nothing

In regular view you could detect that backlog is visible and show the ranking too ...
So it would not be visible just when backlog is collapsed.

So in the end I would go with partial fix + followup issue :)

**Comment by jstourac** [comment]
I agree with Rosta. Having a partial fix will be benefical as one can see the ranking at least in the Rank view itself for now.

**Comment by kabir** [comment]
@jstourac @rsvoboda PR opened
