### ISSUE TITLE
Text search filter

### ISSUE THREAD

**Issue by kabir** [overbaard/overbaard#6]
Should be possible to search for issue key and description text in the control panel. This is especially important now that we use virtual scrolling and not all issues are rendered.

We would need:
* a field for issue ids (with suggestions/autocompletion)
* a field for text in the summaries

There are a few options for how to do this, listed in ease of implementation order.
1. Remove all issues from the board which do not match these filters (similar to what happens when you e.g. select an issue type)
2. Grey out all issues which do not match these filters
2.1. Attempt to scroll to the first matching one (might be hard)
3. Scroll to the first issue (I think this is a poorer solution than 2, and involves what is needed for 2.1)

Also I think the options above don't need to be mutually exclusive. There could be a toggle between options 1 and 2. The question is should this option to toggle be just for these new filter options, or for all the existing filters (project, issue type, priority etc.) too? IOW are they conceptually different or similar to the existing filters? While it could be possible to do this toggle individually for each filter, that sounds too fiddly to be practical.

I have tried to list the options below so you can give thumbs up for the ones you like. If I have missed something add a comment.

**Comment by kabir** [comment]
Option 2

**Comment by kabir** [comment]
Option 3

**Comment by rsvoboda** [comment]
I prefer 2.1 ;)

**Comment by kabir** [comment]
Global toggle

**Comment by kabir** [comment]
Separate toggle for the new filters, and another for the old filters

**Comment by kabir** [comment]
Toggle is just for the new filters

**Comment by mjurc** [comment]
I like the sound of 2.1 too, especially for ranking view :+1:

**Comment by kabir** [comment]
No toggle. The search is considered different from the existing filters. So we use 2.1 for the issue id and text search, while we continue to remove (i.e. option 1) the non-matching issues for the existing filters.
