### ISSUE TITLE
I cannot see any boards in the config page

### ISSUE THREAD

**Issue by markeastman** [overbaard/overbaard#62]
When I go to the config for the boards I see no boards to edit

**Comment by markeastman** [comment]
When I click the config menu item it goes to the page but at the bottom of the page a get an error window pop up with the content:
Http failure response for https://issues.jboss.org/rest/overbaard/1.0/boards?full=true: 500 OK

**Comment by kabir** [comment]
Fixed by https://github.com/overbaard/overbaard/commit/1fdec2ed3538dc33d783a5bb1f56990f4d30a24b
