### ISSUE TITLE
Enhancement - board title to be viewed

### ISSUE THREAD

**Issue by markeastman** [overbaard/overbaard#63]
When viewing a board can we add the title of the board to the title strip of the page perhaps next to the menu and word Overbaard.

**Comment by kabir** [comment]
@markeastman Do you think this should be the code or the name? e.g from our new static demo  site https://overbaard.github.io/demo, would you expect 'DEMO-SIMPLE' or 'Demo board (Simplest Possible)'?

I'd guess the latter, but they could end up being rather long

**Comment by markeastman** [comment]
I will take a look at let you know.  At the LX at the moment

**Comment by kabir** [comment]
Since I am not a web designer, I am a bit worried about cluttering up the clean look. Would putting it in the sidebars or something you hover over in the title bar be an option? Or if you want it visible at all times, perhaps something in the bottom left of the board or something like that.
