### ISSUE TITLE
Issue QL for manual swimlanes and expert issue filtering

### ISSUE THREAD

**Issue by markeastman** [overbaard/overbaard#64]
**NB! - this requirement has been reworked to create a client side query language. This query language can then be used to configure manual swimlanes and improved filtering (beyond what the checkboxes offer). This issue is still used for context**

For labels within issues it would be nice to be able to map some labels (flag indicators really) to have meaningful text. For example in RHMWRT we use RT_MW_PROD_REL to indicate it is a product release issue.

Having a section such as 
```
"lookups" : {
    "labels": {
      "Empty": "Features",
      "RT_MW_PROD_REL": "Product Release"
    }
}
```
Not the use of Empty to indicate those records without any labels (I think it says None at the moment) - we could use that instead of Empty if preferred

**Comment by markeastman** [comment]
Accidentally closed it

**Comment by kabir** [comment]
```
Not the use of Empty to indicate those records without any labels (I think it says None at the moment) - we could use that instead of Empty if preferred
```
@markeastman re ^^ - None currently means it has absolutely no labels. If the absence of RT_MW_PROD_REL means it is a feature, I think this looks like another requirement. I'll ponder it in the back of my mind

**Comment by markeastman** [comment]
What I mean is if you do a swim lane with labels then we get a lane per label, at the bottom we have a lane with the word None (Ie all the issues that have no labels at all), I thought it might be nice to allow the administrator to replace the word None with what ever they like, For us the absence of all labels means something specific - but I don’t think that is a good use!

**Comment by kabir** [comment]
I can replace the text None with whatever as easily as the other ones. But to me giving empty or none special meaning beyond that sounds very fragile. If people start adding ad-hoc labels (e.g. Kabir-sprint1), then those would not appear in the empty swimlane and so they would not get that special meaning.

**Comment by markeastman** [comment]
Agreed - the use fo having RT_MW_PROD_REL or not is not a good approach, I have suggested to John that if he wants to see them like that he could have RT_MW_PROD_REL and RT_MW_FEATURE to distinguish between which ones are field related features and which ones are product releases. - To tell the truth I am not 100% certain of what they really mean to the field, but that is someones else definition. Having the absence of labels should not be construed as anything other than no labels have been set yet.

**Comment by kabir** [comment]
@markeastman I know this kind of 'died'. But I've been thinking about it, and I think perhaps what we need instead is to be able to define swimlanes/filters manually (like Jira has) in addition to the automagic ones Overbård provides.

The pseudo config would be something like:
```
  "custom-selectors": [
    {
      "name": "Feature or Release",
      "options": [
        {
          "name": "Feature",
          "filter": {
            "types": ["Feature"],
            "labels": ["MW_BLAH_BLAH"]
          }
        },
        {
          "name": "Release",
          "filter": {
            "types": ["Feature"],
            "labels": ["!MW_BLAH_BLAH"]
          }
        }
      ]
    }
  ]
```
So each 'custom selector' would appear in the list of swimlanes/filters (e.g. 'Feature or Release' would appear next to Assignee, Priority etc.) and each of the options would be a swimlane/filter entry in that.

That would allow you more 'heterogeneous' choices for swimlanes at least. And although I've only used "types" and "labels" in the example I could add something similar for everything else. I believe this would solve your use-case, and even if you guys probably won't end up using Overbård, I think it would be useful to others. It would also be quite simple to implement, as it is mostly extending the filtering that happens in the UI.

**Comment by markeastman** [comment]
I agree this looks interesting. It would solve our use case and be useful to others as well.

We are moving forward on the Jira overview project for runtimes and I think Overbård will be used on it as it offers a lot of additional visibility.

**Comment by kabir** [comment]
Done by 
https://github.com/overbaard/overbaard/pull/67
